development:
  adapter: postgresql
  encoding: unicode
  database: myRailsApp_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: myRailsApp_test
  pool: 5
  username: postgres
  password: postgres